OUTPUT_PATH: "./cleanArucoMarkersMultiple.png"
BACKGROUND_IMAGE: ""
IMAGE_WIDTH: 640
IMAGE_HEIGHT: 640
ID: [2, 3, 4]
CENTER_X: [100, 320, 500]
CENTER_Y: [100, 480, 200]
OPACITY: [100, 100, 100]
BLUR: [0, 0, 0]
SIZE: [100, 150, 200]