DATA_PATH: "./aruco/"
BACKGROUND_IMAGE_DIR: "./background/"
IMAGE_SIZE: 640
NUM_TRAIN_IMAGES: 200
NUM_TEST_IMAGES: 20
MIN_TAG_COUNT: 1
MAX_TAG_COUNT: 3
MIN_ID: 1
MAX_ID: 50
MIN_OPACITY: 50
MAX_OPACITY: 100
MIN_BLUR: 1
MAX_BLUR: 5
MIN_SIZE: 10
MAX_SIZE: 50